site_title = "ArxivDaily"
limit_days = 7
cache_url = "https://arxiv.alongwy.top/cache.json"

[[sources]]
limit = 100
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 100
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 100
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 100
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 100
category = "cs.MM"
title = "Multimedia"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_meeting = "scripts/highlight_meeting.rhai"
