site_title = "ArxivDaily"
cache_max_days = 7
sources = [
    "http://export.arxiv.org/rss/cs.CL",
    "http://export.arxiv.org/rss/cs.IR",
    "http://export.arxiv.org/rss/cs.MM",
    "http://export.arxiv.org/rss/cs.CV",
    "http://export.arxiv.org/rss/cs.LG"
]
minify = true
cache_url = "https://arxiv.alongwy.top/cache.json"

#proxy = "socks5://127.0.0.1:7890"
[scripts]
download = "scripts/download.rhai"
only_title = "scripts/only_title.rhai"
render_author = "scripts/render_author.rhai"
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"